In [1]:
import numpy as np

In [7]:
A = np.arange(1,9).reshape(2,4)
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
print(A[0])
print(A[0,:])

[1 2 3 4]
[1 2 3 4]


In [10]:
print(A[1])
print(A[1,:])

[5 6 7 8]
[5 6 7 8]


In [12]:
print(A[:,0])
print(A[:,1])
print(A[:,2])
print(A[:,3])

[1 5]
[2 6]
[3 7]
[4 8]


### 행렬의 덧셈 연산

In [14]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[4,1],[5,2]])

In [15]:
A+B

array([[5, 3],
       [8, 6]])

In [16]:
np.add(A,B)

array([[5, 3],
       [8, 6]])

### 행렬의 뺼셈

In [17]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[4,1],[5,2]])

In [18]:
A-B

array([[-3,  1],
       [-2,  2]])

In [19]:
np.subtract(A,B)

array([[-3,  1],
       [-2,  2]])

### 행렬의 스칼라곱

In [20]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
c = 10
A * c

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [22]:
np.multiply(A,c)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

### 행렬의 곱셈

* np.dot()
* A@B

In [24]:
A = np.array([[1,2,3],[4,5,6]])   # 2x3
B = np.array([[4,1],[5,2],[1,2]]) # 3x2

In [25]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
B

array([[4, 1],
       [5, 2],
       [1, 2]])

In [29]:
# 행렬의 곱셈 .dot
A.dot(B)

array([[17, 11],
       [47, 26]])

In [30]:
np.dot(A,B)

array([[17, 11],
       [47, 26]])

In [31]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,1],[5,2]])

In [32]:
A

array([[1, 2],
       [3, 4]])

In [33]:
B

array([[4, 1],
       [5, 2]])

In [34]:
A*B

array([[ 4,  2],
       [15,  8]])

### 전치(transpose)행렬

In [36]:
A = np.arange(1,7). reshape(2,3)

In [37]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [38]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
T = np.array([[1,0,4],[0,1,7],[0,0,1]])
T

array([[1, 0, 4],
       [0, 1, 7],
       [0, 0, 1]])

In [44]:
A =np.array([3,2,1])
A = A.T
A


array([3, 2, 1])

In [46]:
T.dot(A)

array([7, 9, 1])

In [71]:
import numpy as np
degree = 45

M = np.array([[np.cos(degree*np.pi/180),np.sin(degree*np.pi/180),0],[np.sin(degree*np.pi/180),np.cos(degree*np.pi/180),0],[0,0,1]])

p = np. array([7,0,1])
_p =np. dot(M,p)
_p[0]=int(np.round(_p[0]))
_p[1]=int(np.round(_p[1]))
_p[2]=int(np.round(_p[2]))
print(_p)


[5. 5. 1.]


### rotation matrix    

In [72]:
#forward mapping

import cv2
import numpy as np

img = cv2.imread('love.png', cv2.IMREAD_COLOR)
height, width = img.shape[:2]

# 45도를 라디안으로 변환하여 코싸인값과 싸인값을 구합니다.
angle = 45
radian = angle * np.pi / 180
c = np.cos(radian)
s = np.sin(radian)

# 회전변환행렬을 구성합니다.
# OpenCV의 원점이 왼쪽아래가 아니라 왼쪽위라서 [[c, -s, 0], [s, c, 0]]가 아니라
# [[c, s, 0], [-s, c, 0]]입니다.
rotation_matrix = np.array([[c, s, 0], [-s, c, 0], [0, 0, 1]], dtype=float)

dst = np.zeros(img.shape, dtype=np.uint8)

for y in range(height - 1):
    for x in range(width - 1):

        p = np.array([x, y, 1])
        p_ = np.dot(rotation_matrix, p)

        x_, y_ = p_[:2]
        x_ = int(x_)
        y_ = int(y_)

        # 입력 이미지의 픽셀을 가져올 수 있는 경우에만
        # 결과 이미지의 현재 위치의 픽셀로 사용합니다.
        if x_ > 0 and x_ < width and y_ > 0 and y_ < height:
            dst[y_, x_] = img[y, x]

result = cv2.hconcat([img, dst])
cv2.imshow("result", result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [70]:
#backword mapping
import cv2
import numpy as np

img = cv2.imread('love.png', cv2.IMREAD_COLOR)
height, width = img.shape[:2]

# 45도를 라디안으로 변환하여 코싸인값과 싸인값을 구합니다.
angle = 45
radian = angle * np.pi / 180
c = np.cos(radian)
s = np.sin(radian)

# 회전변환행렬을 구성합니다.
# OpenCV의 원점이 왼쪽아래가 아니라 왼쪽위라서 [[c, -s, 0], [s, c, 0]]가 아니라
# [[c, s, 0], [-s, c, 0]]입니다.
rotation_matrix = np.array([[c, s, 0], [-s, c, 0], [0, 0, 1]], dtype=float)

dst = np.zeros(img.shape, dtype=np.uint8)

for y in range(height - 1):
    for x in range(width - 1):

        # 결과 이미지의 픽셀 new_p로 이동하는 입력 이미지의
        # 픽셀 old_p의 위치를 계산합니다.
        new_p = np.array([x, y, 1])
        inv_rotation_matrix = np.linalg.inv(rotation_matrix)
        old_p = np.dot(inv_rotation_matrix, new_p)

        # new_p 위치에 계산하여 얻은 old_p 픽셀의 값을 대입합니다.
        x_, y_ = old_p[:2]
        x_ = int(x_)
        y_ = int(y_)

        # 입력 이미지의 픽셀을 가져올 수 있는 경우에만
        # 결과 이미지의 현재 위치의 픽셀로 사용합니다.
        if x_ > 0 and x_ < width and y_ > 0 and y_ < height:
            dst[y, x] = img[y_, x_]

result = cv2.hconcat([img, dst])
cv2.imshow("result", result)
cv2.waitKey(0)
cv2.destroyAllWindows()