In [4]:
import numpy as np

In [5]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [6]:
print(len(A)) #pycharm
len(A)        # jupyter   


3


3

In [7]:
type(A)

numpy.ndarray

In [8]:
type(A[0])

numpy.int32

In [9]:
B = np.array([list([1, 2, 3]), list([4, 5])], dtype=object)
B

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [12]:
len(B[0])

3

#### Numpy는 성분끼리 연산(vectorization)이 가능 ####
* 파이썬 연산 보다 빠름

In [29]:
A = [1,2,3]
B = [-1,-2,-3]
C = []

In [ ]:
for a,b in zip(A,B):
    C.append(a+b)
C

In [28]:
A = np.array([1,2,3])
B = np.array([-1,-2,-3])
C = A+B  # vectorization
C

array([0, 0, 0])

In [33]:
import numpy as np
a =np.array([0,1,0.2,0.3])
print(a)
a

[0.  1.  0.2 0.3]


array([0. , 1. , 0.2, 0.3])

In [34]:
a.dtype

dtype('float64')

In [39]:
b = np.array([1,2,3])
b.dtype 


dtype('int32')

In [42]:
c =[1,2,3]
c=np.array(c)
c

array([1, 2, 3])

In [43]:
c.dtype

dtype('int32')

#### 자료형을 변환하고 싶을 떄 dtype 사용####
- 원래 자료형이 아닌 다른 자료형으로 변환하고 싶을 때

In [118]:
d=[1,2,3,4]
d=np.array(d,dtype= np.float64)
d.dtype

dtype('float64')

In [117]:
e = [1.,2.,3.,4.]
e = np.array(e)
e.dtype

dtype('float64')

#### NUMPy배열의 type 변환####
* astype()사용

In [120]:
f = np.array([1.1, 2.2, 3.3, 4.9])
f.dtype

dtype('float64')

In [121]:
f=f.astype(np.int32)
f

array([1, 2, 3, 4])

In [122]:
f.shape

(4,)

#### 2차원 Array

In [125]:
A = [[1,2,3],[4,5,6]]
A = np.array(A)

In [126]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
type(A)

numpy.ndarray

#### 차원 표시 : ndim
```
    Array.n
```

In [128]:
A.ndim

2

In [129]:
A.shape

(2, 3)

# 배열에 있는 모든 원소의 개수 size
* size = A.shape

In [130]:
A.size

6

In [131]:
A.dtype

dtype('int32')

In [132]:
A.data

#### 최대 최소 합 평균 구하기
- max
- min
- sum
- .mean

In [135]:
b = np.array([1,2,3,4,5,6])
print('max :',b.max())
print('min :',b.min())
print('sum :',b.sum())
print('mean :',b.mean())

max : 6
min : 1
sum : 21
mean : 3.5


#### 방향성 지정후 연산
* axis =0 / axis =1

In [140]:
c = np.array([[1,2],[3,4]])
print("모든 원소의 합 :",c.sum())
print("열 방향 계산 :",c.sum(axis=0))  #열 방향 계산
print("행 방향 계산 :",c.sum(axis=1))    #행 방향 계산

모든 원소의 합 : 10
열 방향 계산 : [4 6]
행 방향 계산 : [3 7]


In [141]:
c = np.array([[1,2],[3,4]])
print("모든 원소의 최대값 :",c.max())
print("열 방향 계산 :",c.max(axis=0))  #열 방향 계산
print("행 방향 계산 :",c.max(axis=1))    #행 방향 계산

모든 원소의 최대값 : 4
열 방향 계산 : [3 4]
행 방향 계산 : [2 4]


In [156]:
A =np.array([[[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]],
    [[13,14,15,16],
     [17,18,19,20],
     [21,22,23,24]]])
A.shape

(2, 3, 4)

In [157]:
A.ndim

3

In [158]:
A.size

24

In [160]:
A = np.arange(24)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [164]:
A=A.reshape(3,4,2)
A

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [163]:
B=np.arange(10000).reshape(100,100)
B

array([[    1,     2,     3, ...,    98,    99,   100],
       [  101,   102,   103, ...,   198,   199,   200],
       [  201,   202,   203, ...,   298,   299,   300],
       ...,
       [ 9701,  9702,  9703, ...,  9798,  9799,  9800],
       [ 9801,  9802,  9803, ...,  9898,  9899,  9900],
       [ 9901,  9902,  9903, ...,  9998,  9999, 10000]])

#### 파이썬 For연산과 numpy 연산의 비교

In [166]:
import timeit
timeit.timeit('[i**2 for i in A]', setup ='A=range(100)')

4.633697499999471

In [168]:
import timeit
import numpy as np
timeit.timeit('B**2', setup ='import numpy as np; B = np.arange(100)')

0.4316932000001543

In [169]:
import numpy as np
A = np.zeros((2,3))
A

array([[0., 0., 0.],
       [0., 0., 0.]])

In [170]:
A.dtype

dtype('float64')

In [208]:
A = np.zeros((10,10), dtype=np.uint8)

In [171]:
B = np.ones((2,3))
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [172]:
B.dtype

dtype('float64')

In [173]:
C = np.empty((5,5))
C

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.78146964e-307, 1.33511018e-306],
       [1.33511969e-306, 6.23037996e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307],
       [9.34600963e-307, 1.86921143e-306, 6.23061763e-307,
        8.90104239e-307, 8.01089062e-307],
       [1.02359848e-306, 1.60219035e-306, 1.60220393e-306,
        1.05700515e-307, 2.04712906e-306],
       [7.56589622e-307, 1.11258277e-307, 8.90111708e-307,
        1.24604136e-306, 2.56765117e-312]])

In [176]:
D=np.random.random((3,3)) # 0~1사이의 실수값
D

array([[0.51309998, 0.76319992, 0.02469677],
       [0.70841656, 0.47521162, 0.29444705],
       [0.99442256, 0.95570868, 0.50007224]])

#### 정수 랜덤값
- np.random.randint(시작값,끝값,(배열크기(n,m))

In [180]:
E=np.random.randint(1,10,(2,2)) # 0~1사이의 실수값
E

array([[7, 7],
       [7, 4]])

### 연속원소 배열 생성 : np.arange()
- np.arange(마지막값)
- np.arange(시작값,마지막값)
- np.arange(시작값,마지막값,간격)

In [186]:
# 0에서 부터 100까지의 연속된 정수값
A= np.arange(1,101)
A

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [187]:
#1부터 45까지의 연속된 숫자값
A = np.arange(1,46)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [196]:
#0부터 50까지의 5의 배수값(0포함)
A = np.arange(0,51.5)
A

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.])

In [197]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [200]:
B = np.linspace(0,100)
print(B.size)
B


50


array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [209]:
A = np.arange(16)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [210]:
B= A.reshape(4,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [223]:
B1 = A.reshape(4,4).copy()

In [211]:
A[0] =100
B

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [224]:
B1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [216]:
A = np.arange(16)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [217]:
B = A.reshape(4,-1)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [225]:
C =A.reshape(-1,8)
C

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])